title: AIFF
description: > # this means to ignore newlines until "baseurl:"
  Highlighting Emerging Tech Impact on Global Finance
baseurl: "" # the subpath of your site, e.g. /blog
url: "aiff.world" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2018_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/AIFintechForum/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/AIFintechForum/
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty